### ISSUE TITLE
Target data for modules is inaccesable in DiffSwerve

### ISSUE THREAD

**Issue by omagarwal25** [amarcolini/joos#11]
I need to look at the module target headings in order to tune the PID. There are a few ways this can be done

1. Make all the private fields public
2. Expose a function that gets the targets
3. change the private fields to protected and allow users to extend it with their own functionality.

Let me know which one you want and I'll do it.

**Comment by amarcolini** [comment]
Have you tried passing in a config variable for the module PID and tuning that via FTC Dashboard?

**Comment by omagarwal25** [comment]
That's already what I do but it's useful to see target positions and other data. I figured it out though, I just used the Kinematics math. Closing.
