### ISSUE TITLE
Purpose of binding output for Diff Swerve

### ISSUE THREAD

**Issue by omagarwal25** [amarcolini/joos#15]
Hey,

I'm trying to get path following working and it keeps that the modules are having trouble aligning themselves when the robot stops accelerating. 

I was wondering, what's the purpose of binding the output of the module heading controllers? With kP values in the hundreds I that this isn't the best approach and rather the modules should just be allowed to rotate however fast they want to correct for errors. It's on line 99 of the DiffSwerve code

If I'm missing something please let me know, otherwise I'll be filing a PR soon.

        ```leftModuleController.setOutputBounds(-abs(leftAngVel.radians), abs(leftAngVel.radians))```

**Comment by amarcolini** [comment]
In an ideal world that would ensure more accurate following by preventing the robot from exceeding the current target acceleration, but if the robot turns and then drives in a straight line, the target acceleration would be 0, and any errors in module directions wouldn't get fixed until the robot turns again. Maybe I could do something like `leftModuleController.setOutputBounds(-max(someMinRange,abs(leftAngVel.radians)), max(someMinRange, abs(leftAngVel.radians)))` or maybe I could remove it entirely at the cost of slightly jerkier movement. What do you think?

**Comment by omagarwal25** [comment]
I think the later sounds right, because no matter what PID is always adjusting.
