### ISSUE TITLE
Examples?

### ISSUE THREAD

**Issue by omagarwal25** [amarcolini/joos#2]
Hey @amarcolini do you have any examples for the use of Joos? I love what you have here, but I have no idea how to use it, the OpModeClass is very different from anything that I know so far.

**Comment by omagarwal25** [comment]
The robot class seems to want a OP mode, but I'm not really sure where to set it up.

```kt
package org.firstinspires.ftc.teamcode

import com.amarcolini.joos.command.Robot
import com.qualcomm.robotcore.eventloop.opmode.OpMode

class MainRobot() : Robot(TestOpMode()) {
    override fun init() {
        TODO("Not yet implemented")
    }

    override fun start() {
        TODO("Not yet implemented")
    }
}
```
```kt
package org.firstinspires.ftc.teamcode

//import com.qualcomm.robotcore.eventloop.opmode.OpMode
import com.amarcolini.joos.command.RobotOpMode
import com.qualcomm.robotcore.eventloop.opmode.TeleOp

@TeleOp(name = "HaveFun", group = "Two")
class TestOpMode : RobotOpMode() {

    override fun init() {

    }


}

```
This is probably wrong, but how do I use this? Do I have multiple Robots for each of my op modes? Where do I write the actual OP mode code? Thanks!

**Comment by amarcolini** [comment]
Hey @omagarwal25,

Joos is currently in alpha, and as such the API is subject to change. Once it nears completion, I'll release documentation for it. When declaring a Robot, just take an OpMode in the primary constructor and pass it on to the Robot class, and then initialize it in whichever OpMode you'd like. In Kotlin this looks like this:

```kotlin
import com.amarcolini.joos.command.Robot
import com.amarcolini.joos.command.RobotOpMode
import com.qualcomm.robotcore.eventloop.opmode.OpMode
import com.qualcomm.robotcore.eventloop.opmode.TeleOp

class MainRobot(opmode: OpMode) : Robot(opmode) {
    override fun init() {
        TODO("Initialize here")
    }

    override fun start() {
        TODO("Start here")
    }
}

@TeleOp(name = "HaveFun", group = "Two")
class TestOpMode : RobotOpMode() {
    override fun init() {
        initialize(MainRobot(this))
    }
}
```

And in Java like this:

```java
import com.amarcolini.joos.command.Robot;
import com.amarcolini.joos.command.RobotOpMode;
import com.qualcomm.robotcore.eventloop.opmode.OpMode;
import com.qualcomm.robotcore.eventloop.opmode.TeleOp;
import org.jetbrains.annotations.NotNull;

class MainRobot extends Robot {
    public MainRobot(@NotNull OpMode opMode) {
        super(opMode);
    }

    @Override
    public void init() {
        //Initialize here
    }

    @Override
    public void start() {
        //Start here
    }
}

@TeleOp(name = "HaveFun", group = "Two")
class TestOpMode extends RobotOpMode {
    @Override
    public void init() {
        initialize(new MainRobot(this));
    }
}
```

**Comment by omagarwal25** [comment]
Thank you so much for your help @amarcolini . We hope to use joos this season, hopefully, I will be able to help you out with some PRs. Maybe with something like CRS Servos or Sensors. 

Where do I write my actual op mode? Do I just create a function in the bot with the command scheduling and call it in for the op mode?

**Comment by amarcolini** [comment]
Both RobotOpMode and Robot have fields isInTeleOp and isInAutonomous, so from the Robot class you can write both teleop and autonomous code. Init is called once on init, and start is called once on start. You can schedule commands from there, and the RobotOpMode will take care of the rest.

**Comment by omagarwal25** [comment]
Perfect, thanks for your help. For things like the actual driving or mechanisms, I would put those in start right? and then things like resetting servos go in init I assume?

**Comment by amarcolini** [comment]
Yeah. Just be careful when tuning trajectory following. Like I said, Joos is still in alpha, and I haven't worked out all the kinks, so I wouldn't recommend using Joos for that just yet. Happy Coding!
