### ISSUE TITLE
FTC Dashboard not working

### ISSUE THREAD

**Issue by omagarwal25** [amarcolini/joos#6]
Hey,

When I try to open FTCDashboard. I get this error message in the console and a blank white screen
`Uncaught TypeError: navigator.getGamepads is not a function
    t http://192.168.43.1:8080/dash/assets/index.2435614d.js:57
    Bt http://192.168.43.1:8080/dash/assets/index.2435614d.js:57
    i http://192.168.43.1:8080/dash/assets/vendor.24fb0d57.js:31
    _s http://192.168.43.1:8080/dash/assets/vendor.24fb0d57.js:31
    ps http://192.168.43.1:8080/dash/assets/vendor.24fb0d57.js:31
    <anonymous> http://192.168.43.1:8080/dash/assets/index.2435614d.js:57
`

Thanks again for all your help @amarcolini . We at team 19279 really appreciate it.

**Comment by amarcolini** [comment]
I've experienced a similar issue before. What browser are you using?

**Comment by omagarwal25** [comment]
Firefox

**Comment by amarcolini** [comment]
For me, switching to Firefox fixed the issue. I'm not sure what is happening here. Looking in the Dashboard source code, I found [this](https://github.com/acmerobotics/ftc-dashboard/blob/c27aeb71772b7a4f6400d8704da4d1d8d2fdb907/FtcDashboard/dash/src/store/middleware/gamepadMiddleware.ts#L189-L196), but I don't see how that would throw an error. If the problem doesn't resolve, you might want to open an issue on FTC Dashboard's github page.

**Comment by omagarwal25** [comment]
Just to confirm I don't need any custom app for the driver station (the one that connects to the controller)? I just load it onto the control hub right?

**Comment by omagarwal25** [comment]
Ah cheers, @amarcolini I popped it open in Safari and it all works. Weird.
